package com.java.ResturantMgmt.dto;

// default package
// Generated May 18, 2014 11:09:04 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.java.ResturantMgmt.dto.util.GenericDTO;

/**
 * TUserGroup generated by hbm2java
 */
@Entity
@Table(name = "T_USER_GROUP", schema = "HOTELUSER")
public class TUserGroup  extends GenericDTO implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy=GenerationType.SEQUENCE,generator="User_Sequence")
	@SequenceGenerator(
		    name="User_Sequence",
		    sequenceName="User_Sequence",
		    allocationSize=20
		)
	@Column(name = "USER_GROUP_ID", unique = true, nullable = false, precision = 38, scale = 0)
	private Long   userGroupId;
	@Column(name = "USER_GROUP_NAME", nullable = false, length = 50)
	private String userGroupName;
	@Column(name = "USER_GROUP_DESCRIPTION", length = 50)
	private String userGroupDescription;
	@Column(name = "USER_GRP_ACCESS", length = 20)
	private String userGroupAccess;
	@Column(name = "USER_GROUP_STATUS", length = 20)
	private String userGroupStatus;
	@Column(name = "CREATED_BY", nullable = false, length = 50)
	private String createdBy;
	@Column(name = "LAST_UPDATED_BY", nullable = false, length = 50)
	private String lastUpdatedBy;
	@Temporal(TemporalType.DATE)
	@Column(name = "CREATION_DATE")
	private Date   creationDate;
	@Temporal(TemporalType.DATE)
	@Column(name = "LAST_UPDATED_DATE")
	private Date   lastUpdatedDate;
	
	public Long getUserGroupId() {
		return userGroupId;
	}
	public void setUserGroupId(Long userGroupId) {
		this.userGroupId = userGroupId;
	}
	public String getUserGroupName() {
		return userGroupName;
	}
	public void setUserGroupName(String userGroupName) {
		this.userGroupName = userGroupName;
	}
	public String getUserGroupDescription() {
		return userGroupDescription;
	}
	public void setUserGroupDescription(String userGroupDescription) {
		this.userGroupDescription = userGroupDescription;
	}
	public String getUserGroupStatus() {
		return userGroupStatus;
	}
	public void setUserGroupStatus(String userGroupStatus) {
		this.userGroupStatus = userGroupStatus;
	}
	public String getCreatedBy() {
		return createdBy;
	}
	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}
	public String getLastUpdatedBy() {
		return lastUpdatedBy;
	}
	public void setLastUpdatedBy(String lastUpdatedBy) {
		this.lastUpdatedBy = lastUpdatedBy;
	}
	public Date getCreationDate() {
		return creationDate;
	}
	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}
	public Date getLastUpdatedDate() {
		return lastUpdatedDate;
	}
	public void setLastUpdatedDate(Date lastUpdatedDate) {
		this.lastUpdatedDate = lastUpdatedDate;
	}
	public String getUserGroupAccess() {
		return userGroupAccess;
	}
	public void setUserGroupAccess(String userGroupAccess) {
		this.userGroupAccess = userGroupAccess;
	}

	

}
